### ISSUE TITLE
can't be opened

### ISSUE THREAD

**Issue by DanthonyPabon** [aidev1065/Wonderful-Tools-Screensaver#1]
![image](https://user-images.githubusercontent.com/16084773/64820814-36e43880-d57f-11e9-9f1e-311b45d9f1c9.png)

**Comment by zntfdr** [comment]
Hi @DanthonyPabon,
this is a common issue, please refer to [this](https://stackoverflow.com/questions/19551298/app-cant-be-opened-because-it-is-from-an-unidentified-developer/19557149) thread on StackOverflow. 
More specifically the first answer, that I quote here, is the correct way to fix it:
> It's because of the Security options.
>
> Go to System Preferences... > Security & Privacy and there should be a button saying Open Anyway, under the General tab.
>
>You can avoid doing this by changing the options under Allow apps downloaded from:, however I would recommend keeping it at the default Mac App Store and identified developers.

**Comment by BenFryc** [comment]
You can also right-click + open, and then it'll give you the option to open it anyway.
