### ISSUE TITLE
Can't run on Mojave 

### ISSUE THREAD

**Issue by youdy** [aidev1065/Wonderful-Tools-Screensaver#2]
Running 10.14.6 and getting the error "You cannot use this screensaver with this version of the OS" any ideas on how to fix

**Comment by homebysix** [comment]
I'm on 10.14.6, and the screen saver is working OK for me. I dragged and dropped it into ~/Library/Screen Savers.

**Comment by youdy** [comment]
Weirdly enough it displays this on the screensavers menu within system preferences but still works. 🤷🏻‍♂️
