### ISSUE TITLE
Requires update to run with Big Sur

### ISSUE THREAD

**Issue by matthewbuchanan** [aidev1065/Wonderful-Tools-Screensaver#6]
I see an OS message about Apple being unable to check the screensaver for malicious software. Any chance of an updated build to allow this to run on Big Sur? Thanks.

<img width="260" alt="Screen Shot 2021-07-01 at 1 45 06 PM" src="https://user-images.githubusercontent.com/531516/124052505-a5ef9180-da72-11eb-8f82-f8c290da920a.png">

**Comment by heysaik** [comment]
I believe if you go into System Preferences and Security, you should be able to manually approve the screensaver.
